/**
 * Shared export utilities — CSV, Excel (exceljs, styled), PDF (jspdf + autotable).
 * All three formats follow the Microgenesis Export Formatting Standard:
 *   - 3-row metadata header before data
 *   - Navy (#1F3864) header row, white bold text
 *   - Title-Case column headers, no snake_case
 *   - Date: "Jul 17, 2026" | Time: "9:32 AM"
 *   - Footer row with total count
 */

export interface ExportColumn {
  header: string;
  key: string;
  width?: number;         // Excel column width (chars)
  pdfWidth?: number;      // PDF column width (mm); omit for auto
  pdfPill?: boolean;      // Render cell as a colored status pill in PDF
  pdfAlign?: 'left' | 'center' | 'right';
}

export interface ExportMeta {
  reportName: string;
  dateRange?: string;
  generatedByName: string;
  generatedByRole: string;
}

export interface StatusHistoryCounts {
  ever_held: Record<string, number>;
  current: Record<string, number>;
  total_records: number;
}

// ─── Formatters ───────────────────────────────────────────────────────────────

export function fmtDate(s: string | null | undefined): string {
  if (!s) return '';
  const d = new Date(s.includes('T') ? s : `${s}T12:00:00`);
  if (isNaN(d.getTime())) return s;
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export function fmtTime(s: string | null | undefined): string {
  if (!s) return '';
  const d = new Date(s);
  if (isNaN(d.getTime())) return '';
  return d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', hour12: true });
}

export function fmtDatetime(s: string | null | undefined): string {
  if (!s) return '';
  const date = fmtDate(s);
  const time = fmtTime(s);
  return date && time ? `${date} ${time}` : date || time;
}

export function fmtStatus(s: string | null | undefined): string {
  if (!s) return '';
  return s.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

export function fmtCurrency(n: number | null | undefined): string {
  if (n == null) return '';
  return '₱' + n.toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

// ─── CSV Export ───────────────────────────────────────────────────────────────

const STATUS_ORDER = ['Scheduled', 'Delivered', 'Pending', 'On-Hold', 'Rescheduled'] as const;

export function downloadCSV(
  rows: Record<string, string | number | null | undefined>[],
  columns: ExportColumn[],
  filename: string,
  meta: ExportMeta,
  statusHistoryCounts?: StatusHistoryCounts
): void {
  const now = new Date();
  const dateStr = fmtDate(now.toISOString());
  const timeStr = fmtTime(now.toISOString());
  const reportLine = meta.dateRange
    ? `${meta.reportName} — ${meta.dateRange}`
    : meta.reportName;

  const metaRows = [
    ['Microgenesis Business Systems'],
    [reportLine],
    [`Generated by: ${meta.generatedByName} (${meta.generatedByRole}) on ${dateStr} at ${timeStr}`],
    []
  ];

  const summaryRows: string[][] = [];
  if (statusHistoryCounts) {
    summaryRows.push(['STATUS HISTORY SUMMARY']);
    summaryRows.push([
      'Status',
      'Ever Held (historical — records counted in each status they passed through)',
      'Current Status (each record counted once)'
    ]);
    for (const s of STATUS_ORDER) {
      summaryRows.push([s, String(statusHistoryCounts.ever_held[s] ?? 0), String(statusHistoryCounts.current[s] ?? 0)]);
    }
    summaryRows.push(['Total Records', String(statusHistoryCounts.total_records), String(statusHistoryCounts.total_records)]);
    summaryRows.push(['* Ever Held counts may exceed total records as one record can pass through multiple statuses over its lifetime.']);
    summaryRows.push([]);
  }

  const headerRow = columns.map(c => c.header);

  const dataRows = rows.map(r =>
    columns.map(c => {
      const v = r[c.key];
      return v == null ? '' : String(v);
    })
  );

  const footerRow = [`Total Records: ${rows.length}`, ...Array(columns.length - 1).fill('')];

  const allRows = [...metaRows, ...summaryRows, headerRow, ...dataRows, footerRow];

  const csv = allRows
    .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\r\n');

  const blob = new Blob(['﻿' + csv, { type: 'text/csv;charset=utf-8;' }] as unknown as BlobPart[]);
  const url = URL.createObjectURL(new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8;' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}-${now.toISOString().split('T')[0]}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Excel Export (exceljs — styled) ─────────────────────────────────────────

const NAVY = 'FF1F3864';
const WHITE = 'FFFFFFFF';
const GRAY_ROW = 'FFF8F9FA';

const STATUS_EXCEL_COLORS: Record<string, string> = {
  'Scheduled':   'FF2563EB',
  'Delivered':   'FF059669',
  'Pending':     'FFD97706',
  'On-Hold':     'FFDC2626',
  'Rescheduled': 'FF7C3AED',
};

export async function downloadExcel(
  rows: Record<string, string | number | null | undefined>[],
  columns: ExportColumn[],
  sheetName: string,
  filename: string,
  meta: ExportMeta,
  statusHistoryCounts?: StatusHistoryCounts
): Promise<void> {
  const ExcelJS = (await import('exceljs')).default;
  const wb = new ExcelJS.Workbook();
  wb.creator = meta.generatedByName;
  wb.created = new Date();

  const ws = wb.addWorksheet(sheetName);

  const now = new Date();
  const dateStr = fmtDate(now.toISOString());
  const timeStr = fmtTime(now.toISOString());
  const reportLine = meta.dateRange
    ? `${meta.reportName} — ${meta.dateRange}`
    : meta.reportName;

  // ── Row 1: Company name ───────────────────────────────────────────────────
  const r1 = ws.addRow(['Microgenesis Business Systems']);
  r1.getCell(1).font = { bold: true, size: 14, color: { argb: NAVY } };

  // ── Row 2: Report name + date range ──────────────────────────────────────
  const r2 = ws.addRow([reportLine]);
  r2.getCell(1).font = { size: 11, color: { argb: NAVY } };

  // ── Row 3: Generated by ───────────────────────────────────────────────────
  const r3 = ws.addRow([
    `Generated by: ${meta.generatedByName} (${meta.generatedByRole}) on ${dateStr} at ${timeStr}`
  ]);
  r3.getCell(1).font = { size: 10, italic: true, color: { argb: 'FF64748B' } };

  // ── Row 4: Blank ─────────────────────────────────────────────────────────
  ws.addRow([]);

  // ── Summary table (rows 5–14 when present) ────────────────────────────────
  let summaryRowCount = 0;
  if (statusHistoryCounts) {
    // Title row
    const sTitle = ws.addRow(['STATUS HISTORY SUMMARY']);
    sTitle.getCell(1).font = { bold: true, size: 11, color: { argb: NAVY } };
    sTitle.height = 18;

    // Header row
    const sHeader = ws.addRow(['Status', 'Ever Held', 'Current Status']);
    sHeader.eachCell((cell, col) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
      cell.font = { bold: true, color: { argb: WHITE }, size: 10 };
      cell.alignment = { vertical: 'middle', horizontal: col === 1 ? 'left' : 'center' };
      cell.border = {
        top: { style: 'thin', color: { argb: NAVY } },
        bottom: { style: 'thin', color: { argb: NAVY } },
        left: { style: 'thin', color: { argb: 'FFD0D0D0' } },
        right: { style: 'thin', color: { argb: 'FFD0D0D0' } }
      };
    });
    sHeader.height = 18;

    // Status rows
    for (const s of STATUS_ORDER) {
      const sRow = ws.addRow([s, statusHistoryCounts.ever_held[s] ?? 0, statusHistoryCounts.current[s] ?? 0]);
      const color = STATUS_EXCEL_COLORS[s] ?? NAVY;
      sRow.getCell(1).font = { bold: true, color: { argb: color }, size: 10 };
      sRow.getCell(2).alignment = { horizontal: 'center' };
      sRow.getCell(3).alignment = { horizontal: 'center' };
      sRow.eachCell({ includeEmpty: true }, cell => {
        cell.border = {
          bottom: { style: 'hair', color: { argb: 'FFE2E8F0' } },
          left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
          right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
        };
      });
      sRow.height = 16;
    }

    // Total row
    const sTot = ws.addRow(['Total Records', statusHistoryCounts.total_records, statusHistoryCounts.total_records]);
    sTot.getCell(1).font = { bold: true, size: 10, color: { argb: NAVY } };
    sTot.getCell(2).font = { bold: true, size: 10 };
    sTot.getCell(2).alignment = { horizontal: 'center' };
    sTot.getCell(3).font = { bold: true, size: 10 };
    sTot.getCell(3).alignment = { horizontal: 'center' };
    sTot.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEEF2FF' } };
    sTot.getCell(2).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEEF2FF' } };
    sTot.getCell(3).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEEF2FF' } };
    sTot.height = 16;

    // Footnote
    const sNote = ws.addRow(['* Ever Held counts may exceed total records as one record can pass through multiple statuses over its lifetime.']);
    sNote.getCell(1).font = { italic: true, size: 8, color: { argb: 'FF64748B' } };
    sNote.height = 14;

    // Blank separator
    ws.addRow([]);

    // 1 title + 1 header + 5 status + 1 total + 1 footnote + 1 blank = 10
    summaryRowCount = 10;
  }

  // ── Column headers ────────────────────────────────────────────────────────
  const headerRow = ws.addRow(columns.map(c => c.header));
  headerRow.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: NAVY } };
    cell.font = { bold: true, color: { argb: WHITE }, size: 10 };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
    cell.border = {
      top: { style: 'thin', color: { argb: NAVY } },
      bottom: { style: 'thin', color: { argb: NAVY } },
      left: { style: 'thin', color: { argb: 'FFD0D0D0' } },
      right: { style: 'thin', color: { argb: 'FFD0D0D0' } }
    };
  });
  headerRow.height = 22;

  // ── Data rows ─────────────────────────────────────────────────────────────
  rows.forEach((r, idx) => {
    const dataRow = ws.addRow(columns.map(c => {
      const v = r[c.key];
      return v == null ? '' : v;
    }));
    const isAlt = idx % 2 === 1;
    dataRow.eachCell({ includeEmpty: true }, cell => {
      if (isAlt) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: GRAY_ROW } };
      }
      cell.font = { size: 10 };
      cell.border = {
        bottom: { style: 'hair', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } }
      };
      cell.alignment = { vertical: 'middle', wrapText: false };
    });
    dataRow.height = 18;
  });

  // ── Footer row ────────────────────────────────────────────────────────────
  const footerRow = ws.addRow([`Total Records: ${rows.length}`]);
  footerRow.getCell(1).font = { bold: true, italic: true, size: 10, color: { argb: NAVY } };
  footerRow.getCell(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFEEF2FF' } };

  // ── Column widths ─────────────────────────────────────────────────────────
  ws.columns = columns.map(c => ({
    width: Math.max(c.width ?? 18, c.header.length + 4)
  }));

  // ── Merge meta rows across all columns ───────────────────────────────────
  const colCount = columns.length;
  if (colCount > 1) {
    ws.mergeCells(1, 1, 1, colCount);
    ws.mergeCells(2, 1, 2, colCount);
    ws.mergeCells(3, 1, 3, colCount);
    if (summaryRowCount > 0) {
      // Merge summary title and footnote across all columns
      ws.mergeCells(5, 1, 5, colCount);
      ws.mergeCells(5 + 1 + STATUS_ORDER.length + 2, 1, 5 + 1 + STATUS_ORDER.length + 2, colCount);
    }
    const footerRowNum = 4 + summaryRowCount + 1 + rows.length + 1;
    ws.mergeCells(footerRowNum, 1, footerRowNum, colCount);
  }

  // ── Download ──────────────────────────────────────────────────────────────
  const buffer = await wb.xlsx.writeBuffer();
  const blob = new Blob([buffer], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}-${now.toISOString().split('T')[0]}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── PDF Export (jspdf + jspdf-autotable) ────────────────────────────────────

async function loadLogoBase64(): Promise<string | null> {
  try {
    const res = await fetch('/microgenesis_logo.png');
    if (!res.ok) return null;
    const blob = await res.blob();
    return new Promise(resolve => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

// Status → RGB fill color for pill badges
const PILL_COLORS: Record<string, [number, number, number]> = {
  'delivered':    [5,   150, 105],  // emerald-600
  'accomplished': [5,   150, 105],
  'scheduled':    [37,  99,  235],  // blue-600
  'in progress':  [37,  99,  235],
  'in-progress':  [37,  99,  235],
  'pending':      [217, 119, 6],    // amber-600
  'rescheduled':  [124, 58,  237],  // violet-600
  'on hold':      [220, 38,  38],   // red-600
  'on-hold':      [220, 38,  38],
  'cancelled':    [107, 114, 128],  // gray-500
  'overdue':      [220, 38,  38],
  'yes':          [5,   150, 105],
  'no':           [107, 114, 128],
  'verified':     [5,   150, 105],
};

export async function downloadPDF(
  rows: Record<string, string | number | null | undefined>[],
  columns: ExportColumn[],
  title: string,
  filename: string,
  meta: ExportMeta,
  landscape = true,
  statusHistoryCounts?: StatusHistoryCounts
): Promise<void> {
  const { jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF({
    orientation: landscape ? 'landscape' : 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const now = new Date();
  const dateStr = fmtDate(now.toISOString());
  const timeStr = fmtTime(now.toISOString());
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const NAVY_RGB: [number, number, number] = [31, 56, 100];

  // ── Logo (top-left) ───────────────────────────────────────────────────────
  const logo = await loadLogoBase64();
  if (logo) {
    doc.addImage(logo, 'PNG', 10, 5, 32, 11);
  }

  // ── Title — most dominant element: bold, near-black, 17pt ────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.setTextColor(17, 24, 39);
  doc.text(title, pageW / 2, 13, { align: 'center' });

  if (meta.dateRange) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(meta.dateRange, pageW / 2, 18, { align: 'center' });
  }

  // ── Top-right: generated by ───────────────────────────────────────────────
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  doc.setTextColor(148, 163, 184);
  doc.text(
    `Generated by ${meta.generatedByName} (${meta.generatedByRole})`,
    pageW - 10, 8, { align: 'right' }
  );
  doc.text(`${dateStr}  at  ${timeStr}`, pageW - 10, 12.5, { align: 'right' });

  // ── Navy horizontal rule ──────────────────────────────────────────────────
  const headerEndY = meta.dateRange ? 23 : 20;
  doc.setDrawColor(...NAVY_RGB);
  doc.setLineWidth(0.5);
  doc.line(10, headerEndY, pageW - 10, headerEndY);

  // ── Status history summary table ──────────────────────────────────────────
  let mainTableStartY = headerEndY + 3;
  if (statusHistoryCounts) {
    const summaryBody = STATUS_ORDER.map(s => [
      s,
      String(statusHistoryCounts.ever_held[s] ?? 0),
      String(statusHistoryCounts.current[s] ?? 0),
    ]);
    summaryBody.push(['Total Records', String(statusHistoryCounts.total_records), String(statusHistoryCounts.total_records)]);

    autoTable(doc, {
      head: [['Status', 'Ever Held', 'Current Status']],
      body: summaryBody,
      startY: headerEndY + 3,
      margin: { left: 10, right: 10 },
      tableWidth: 120,
      styles: { fontSize: 8, cellPadding: { top: 2, right: 4, bottom: 2, left: 4 } },
      headStyles: { fillColor: NAVY_RGB, textColor: [255, 255, 255], fontStyle: 'bold', halign: 'center' },
      columnStyles: {
        0: { halign: 'left', fontStyle: 'bold' },
        1: { halign: 'center' },
        2: { halign: 'center' },
      },
      didDrawPage: () => {},
    });

    const summaryFinalY = (doc as any).lastAutoTable?.finalY ?? headerEndY + 30;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(6.5);
    doc.setTextColor(100, 116, 139);
    doc.text(
      '* Ever Held counts may exceed total records as one record can pass through multiple statuses over its lifetime.',
      10, summaryFinalY + 4
    );
    mainTableStartY = summaryFinalY + 10;
  }

  // ── Pill column index set ─────────────────────────────────────────────────
  const pillCols = new Set<number>(
    columns.reduce<number[]>((acc, col, i) => { if (col.pdfPill) acc.push(i); return acc; }, [])
  );

  // ── Table ─────────────────────────────────────────────────────────────────
  // jsPDF's built-in Helvetica uses WinAnsi encoding; U+20B1 (₱) is not in
  // the charset and gets mapped to 0xB1 (±), which also corrupts the internal
  // text-width metrics and causes adjacent text (e.g. ".00") to be clipped.
  // Replace ₱ with the ISO-safe "PHP " prefix for all PDF cell values.
  const pdfSafe = (v: string | number | null | undefined) =>
    v == null ? '' : String(v).replace(/₱/g, 'PHP ');

  const tableBody = rows.map(r =>
    columns.map(c => pdfSafe(r[c.key]))
  );

  autoTable(doc, {
    head: [columns.map(c => c.header)],
    body: tableBody,
    startY: mainTableStartY,
    margin: { left: 10, right: 10 },
    tableWidth: 'auto',
    styles: {
      fontSize: 8,
      cellPadding: { top: 2.5, right: 3.5, bottom: 2.5, left: 3.5 },
      lineColor: [226, 232, 240],
      lineWidth: 0.2,
      overflow: 'linebreak',
    },
    headStyles: {
      fillColor: NAVY_RGB,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
      halign: 'center',
      valign: 'middle',
      minCellHeight: 9,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    bodyStyles: {
      textColor: [30, 41, 59],
      minCellHeight: 9,
      valign: 'middle',
    },
    columnStyles: Object.fromEntries(
      columns.map((col, i) => [i, {
        cellWidth: col.pdfWidth ?? 'auto',
        halign: col.pdfAlign ?? (pillCols.has(i) ? 'center' : 'left'),
      }])
    ),
    // Suppress default text for pill cells so we can draw the badge manually
    willDrawCell: (data: any) => {
      if (data.section === 'body' && pillCols.has(data.column.index)) {
        data.cell.text = [];
      }
    },
    // Draw colored status pills
    didDrawCell: (data: any) => {
      if (data.section !== 'body' || !pillCols.has(data.column.index)) return;
      const text = String(data.cell.raw ?? '').trim();
      if (!text) return;
      const color: [number, number, number] = PILL_COLORS[text.toLowerCase()] ?? [107, 114, 128];
      const cw = data.cell.width;
      const ch = data.cell.height;
      const cx = data.cell.x;
      const cy = data.cell.y;
      const pillW = Math.min(cw - 6, 32);
      const pillH = 5.5;
      const pillX = cx + (cw - pillW) / 2;
      const pillY = cy + (ch - pillH) / 2;
      doc.setFillColor(color[0], color[1], color[2]);
      doc.roundedRect(pillX, pillY, pillW, pillH, 1.4, 1.4, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(6.5);
      doc.setFont('helvetica', 'bold');
      doc.text(text, pillX + pillW / 2, pillY + pillH / 2 + 0.4, {
        align: 'center',
        baseline: 'middle',
      });
      // Reset font for subsequent cells
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(30, 41, 59);
    },
    rowPageBreak: 'avoid',
    didDrawPage: (data: any) => {
      const pageCount = (doc as any).internal.getNumberOfPages();
      const currentPage = data.pageNumber;

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(148, 163, 184);
      doc.text(`${dateStr} at ${timeStr}`, 10, pageH - 5);
      doc.text('Microgenesis Business Systems — Confidential', pageW / 2, pageH - 5, { align: 'center' });
      doc.text(`Page ${currentPage} of ${pageCount}`, pageW - 10, pageH - 5, { align: 'right' });

      if (currentPage > 1) {
        doc.setDrawColor(...NAVY_RGB);
        doc.setLineWidth(0.3);
        doc.line(10, 8, pageW - 10, 8);
      }
    },
  });

  // ── Total count after table ───────────────────────────────────────────────
  const finalY = (doc as any).lastAutoTable?.finalY ?? headerEndY + 10;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(...NAVY_RGB);
  doc.text(`Total Records: ${rows.length}`, 10, finalY + 6);

  doc.save(`${filename}-${now.toISOString().split('T')[0]}.pdf`);
}

// ─── Column definitions per module ───────────────────────────────────────────

export const DELIVERY_COLUMNS: ExportColumn[] = [
  { header: 'Record ID',         key: 'id',               width: 18 },
  { header: 'Company Name',      key: 'company_name',      width: 28 },
  { header: 'Reference Number',  key: 'reference',         width: 22 },
  { header: 'Category',          key: 'category',          width: 24 },
  { header: 'Priority',          key: 'priority',          width: 20 },
  { header: 'Area',              key: 'area',              width: 18 },
  { header: 'Delivery Date',     key: 'delivery_date_fmt', width: 18 },
  { header: 'Driver',            key: 'driver',            width: 24 },
  { header: 'Driver Assistant',  key: 'driver_assistant',  width: 24 },
  { header: 'Account Manager',   key: 'account_manager',   width: 24 },
  { header: 'Vehicle',           key: 'vehicle',           width: 18 },
  { header: 'Item Type',         key: 'item_type',         width: 16 },
  { header: 'Status',            key: 'status_fmt',        width: 14 },
  { header: 'Remarks',           key: 'remarks',           width: 36 },
  { header: 'Created By',        key: 'created_by',        width: 24 },
  { header: 'Created At',        key: 'created_at_fmt',    width: 22 },
];

export const AC_EXTRA_COLUMNS: ExportColumn[] = [
  { header: 'Amount (₱)',         key: 'amount_fmt',             width: 18 },
  { header: 'Collection Verified', key: 'collection_verified_fmt', width: 20 },
  { header: 'Verified By',         key: 'collection_verified_by',  width: 24 },
  { header: 'Verified At',         key: 'collection_verified_at_fmt', width: 22 },
];

// ─── PDF-specific column sets (tighter, screen-matched) ──────────────────────
// These are used only for PDF. CSV/Excel still uses DELIVERY_COLUMNS for full data.

export const PDF_DELIVERY_COLUMNS: ExportColumn[] = [
  { header: 'Record ID',       key: 'id',                width: 18, pdfWidth: 20                       },
  { header: 'Company',         key: 'company_name',      width: 28, pdfWidth: 58                       },
  { header: 'Reference No.',   key: 'reference',         width: 22, pdfWidth: 26                       },
  { header: 'Priority',        key: 'priority',          width: 16, pdfWidth: 22                       },
  { header: 'Area',            key: 'area',              width: 22, pdfWidth: 32                       },
  { header: 'Delivery Date',   key: 'delivery_date_fmt', width: 18, pdfWidth: 22                       },
  { header: 'Driver',          key: 'driver',            width: 24, pdfWidth: 30                       },
  { header: 'Account Manager', key: 'account_manager',   width: 20, pdfWidth: 24                       },
  { header: 'Status',          key: 'status_fmt',        width: 14, pdfWidth: 26, pdfPill: true, pdfAlign: 'center' },
];

// AC widths sum to 257mm — comfortably under the 277mm landscape usable width.
// Amount is 32mm: ₱1,000,000.00 (worst case) needs ~20mm text + 7mm padding = 27mm;
// 32mm gives 5mm breathing room and prevents jspdf clipping on unbreakable currency strings.
export const PDF_AC_COLUMNS: ExportColumn[] = [
  { header: 'Record ID',       key: 'id',                       width: 18, pdfWidth: 20                       },
  { header: 'Company',         key: 'company_name',              width: 28, pdfWidth: 53                       },
  { header: 'Reference No.',   key: 'reference',                 width: 22, pdfWidth: 24                       },
  { header: 'Priority',        key: 'priority',                  width: 16, pdfWidth: 20                       },
  { header: 'Date',            key: 'delivery_date_fmt',         width: 18, pdfWidth: 22                       },
  { header: 'Area',            key: 'area',                      width: 22, pdfWidth: 26                       },
  { header: 'Account Manager', key: 'account_manager',           width: 20, pdfWidth: 22                       },
  { header: 'Amount (PHP)',      key: 'amount_fmt',                width: 18, pdfWidth: 32, pdfAlign: 'right'    },
  { header: 'Status',          key: 'status_fmt',                width: 14, pdfWidth: 24, pdfPill: true, pdfAlign: 'center' },
  { header: 'Verified',        key: 'collection_verified_fmt',   width: 16, pdfWidth: 18, pdfPill: true, pdfAlign: 'center' },
];

export const SKU_COLUMNS: ExportColumn[] = [
  { header: 'SKU Code',          key: 'sku_code',           width: 18 },
  { header: 'Product Name',      key: 'name',               width: 32 },
  { header: 'Category',          key: 'category',           width: 12 },
  { header: 'Unit Cost',         key: 'unit_cost_fmt',      width: 16 },
  { header: 'Unit Price',        key: 'unit_price_fmt',     width: 16 },
  { header: 'Reorder Point',     key: 'reorder_point',      width: 16 },
  { header: 'On-Hand Qty',       key: 'on_hand_qty',        width: 14 },
  { header: 'Allocated Qty',     key: 'allocated_qty',      width: 14 },
  { header: 'ATP',               key: 'atp',                width: 12 },
  { header: 'Warehouse Location',key: 'warehouse_location', width: 22 },
  { header: 'Description',       key: 'description',        width: 36 },
  { header: 'Created By',        key: 'created_by',         width: 22 },
  { header: 'Modified By',       key: 'modified_by',        width: 22 },
];

export const TXN_COLUMNS: ExportColumn[] = [
  { header: 'Reference',      key: 'reference',   width: 22 },
  { header: 'Type',           key: 'type',        width: 20 },
  { header: 'Source',         key: 'source',      width: 14 },
  { header: 'Entity',         key: 'entity',      width: 30 },
  { header: 'Status',         key: 'status',      width: 14 },
  { header: 'Date',           key: 'date_fmt',    width: 18 },
  { header: 'Description',    key: 'description', width: 36 },
  { header: 'Qty Change',     key: 'qty_change',  width: 14 },
  { header: 'Balance',        key: 'balance',     width: 14 },
  { header: 'Created By',     key: 'created_by',  width: 22 },
];

export const CUSTOMER_COLUMNS: ExportColumn[] = [
  { header: 'Account ID',     key: 'id',             width: 18 },
  { header: 'Merchant Name',  key: 'name',           width: 32 },
  { header: 'Contact Person', key: 'contact_person', width: 24 },
  { header: 'Email',          key: 'email',          width: 28 },
  { header: 'Phone',          key: 'phone',          width: 18 },
  { header: 'City',           key: 'city',           width: 18 },
  { header: 'Address',        key: 'address',        width: 36 },
  { header: 'Total Records',  key: 'total_records',  width: 16 },
];

export const SUPPLIER_COLUMNS: ExportColumn[] = [
  { header: 'Supplier ID',    key: 'id',             width: 18 },
  { header: 'Supplier Name',  key: 'name',           width: 32 },
  { header: 'Contact Person', key: 'contact_person', width: 24 },
  { header: 'Email',          key: 'email',          width: 28 },
  { header: 'Phone',          key: 'phone',          width: 18 },
  { header: 'City',           key: 'city',           width: 18 },
  { header: 'Address',        key: 'address',        width: 36 },
  { header: 'Category',       key: 'category',       width: 18 },
  { header: 'Pick-ups',       key: 'pickup_count',   width: 14 },
];

export const WAREHOUSE_COLUMNS: ExportColumn[] = [
  { header: 'Bin Code',       key: 'bin_code',       width: 14 },
  { header: 'Zone',           key: 'zone',           width: 10 },
  { header: 'SKU Code',       key: 'sku_code',       width: 16 },
  { header: 'SKU Name',       key: 'sku_name',       width: 30 },
  { header: 'Category',       key: 'category',       width: 12 },
  { header: 'On Hand',        key: 'on_hand_qty',    width: 12 },
  { header: 'Allocated',      key: 'allocated_qty',  width: 12 },
  { header: 'ATP',            key: 'atp',            width: 10 },
  { header: 'Reorder Point',  key: 'reorder_point',  width: 14 },
  { header: 'Low Stock',      key: 'low_stock',      width: 12 },
];
